---
title: "final_alpha"
output: html_document
date: '2022-08-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading packages
library(pacman)
p_load(
   dplyr,
   ggplot2,
   magrittr,
   tidyr,
   stringr
)
```

Showing loaded packages and version
```{r}
(.packages()) # To check packages
R.version.string$rv
```


*****

## Cleaning and Reshaping Data

### Part 1 of Data

```{r}
# Importing the data
bdf1 = read.csv("pre_2_10_22_data_of_B.csv")

# Showing preview of data
skimr::skim(bdf1)
```

```{r message=FALSE, warning=FALSE}
bdf1a = bdf1 %>% # Preserving original data frame
       separate(time_out, c("hour_out","minute_out",sep = ":")) %>%
       separate(time_in, c("hour_in","minute_in",sep = ":")) %>%
       mutate(ind = as.factor(ind),
              ind_0 = if_else(ind==0,T,F),
              ind_1 = if_else(ind==1,T,F),
              ind_2 = if_else(ind==2,T,F),
              "Δ" = "--") %>%
       rename(Date = date, Urine = urine, Stool = shit, AM_PM = am_or_pm)

# Loading data on other dog to construct `both` column
sdf1 = read.csv("pre_2_10_22_data_of_s.csv")

```

### Part 2 of Data

```{r}
# Importing the data
bdf2 = read.csv("2.10_thru_3.24.csv")

# Showing preview of data
skimr::skim(bdf2)
```

```{r message=FALSE, warning=FALSE}
bdf2a = bdf2 %>% # To preserve original data frame
   filter(Which.Dog.!="Siobhan") %>% # only looking at one dog
   separate(Timestamp,
            c("Date", "Time"), # Separating time stamp at column spacing
            sep = " ") %>% 
   rename("Stool" = "Shit") %>% # Renaming for civility's sake
   mutate(both = if_else(`Which.Dog.`=="Both", TRUE, FALSE),
          id = row_number()) %>%
   select(-c("Time","Which.Dog.")) # No longer needing these columns
   
# Indicator value for urination and stool during outing
bdf2a$Urine <- substr(bdf2a$Urine,1,1)
bdf2a$Stool <- substr(bdf2a$Stool,1,1)

# Separating AM/PM from time stamp
am_pm_nchar = 2                               
bdf2a$AM_PM = substr(bdf2a$Time.In,
       nchar(bdf2a$Time.In) - am_pm_nchar + 1,
       nchar(bdf2a$Time.In))

bdf2a %<>% rename(ind = Indicator.Value, DATE = Date)
bdf2a$ind <- substr(bdf2a$ind,1,1)
bdf2a %<>% mutate(ind = as.factor(ind),
                  ind_0 = if_else(ind==0,T,F),
                  ind_1 = if_else(ind==1,T,F),
                  ind_2 = if_else(ind==2,T,F),
                  "Δ" = "--", # Placeholder for variable
                  id = as.character(id)) %>%
           separate(Time.Out, c("HOUR_OUT","MIN_OUT",":"), remove = T) %>%
           separate(Time.In, c("HOUR_IN","MINUTE_IN",":"), remove = T) %>%
           select(-c(":"))

# Reordering columns for merging files
bdf3a <- bdf2a[, c(1,3,4,12,6,7,16,5,8,13,14,15,9)]
```

Verifying matching formatting before merging sets
```{r}
str(bdf1a); str(bdf2a)
```




Taking a look at the notes section to see commonly reported notes

```{r}

```



## Dealing with Missing Values

```{r}

```

# 12 hour cycle
# 24 hour cycle
add variable for "normal sleeping hours"
